export const ANALYTICS_EVENTS = [
  'app_opened',
  'page_viewed',
  'account_created',
  'onboarding_completed',
  'starter_plan_shown',
  'starter_plan_accepted',
  'starter_plan_skipped',
  'starter_plan_day_start',
  'task_created',
  'task_completed',
  'task_reopened',
  'timer_started',
  'timer_completed',
  'quest_objective_claimed',
  'quest_objective_rerolled',
  'quest_ladder_finished',
  'daily_reward_claimed',
  'ad_requested',
  'ad_ready',
  'ad_impression',
  'ad_completed',
  'ad_dismissed',
  'ad_failed',
  'ad_consent_resolved',
  'ad_consent_failed',
  'paywall_viewed',
  'paywall_step_viewed',
  'purchase_started',
  'purchase_completed',
  'purchase_cancelled',
  'purchase_failed',
  'subscription_started',
  'subscription_renewed',
  'subscription_cancelled',
  'subscription_expired',
  'subscription_billing_issue',
  'subscription_refunded',
  'subscription_product_changed',
  'try_funnel_viewed',
  'try_task_completed',
  'try_gift_opened',
  'try_signin_started',
  'try_signup_completed',
  'try_gift_claimed',
  'try_cosmetic_previewed',
  'try_continued',
  'try_store_clicked',
  'fly_game_viewed',
  'fly_game_started',
  'fly_game_completed',
  'fly_game_shared',
  'fly_game_signup_clicked',
  'fly_game_high_score_gift',
  'fly_game_run_gift',
  'fly_earned',
  'fly_spent',
  'skin_purchased',
  'skin_traded',
  'season_reward_claimed',
  'season_tier_purchased',
  'referral_invite_created',
  'referral_invite_shared',
  'referral_invite_opened',
  'referral_invite_claimed',
  'friend_link_shared',
  'friend_link_opened',
  'friend_request_sent',
  'friend_request_accepted',
  'friend_request_declined',
  'friend_removed',
  'buddy_flow_opened',
  'buddy_friend_picked',
  'buddy_goal_composed',
  'buddy_invite_sent',
  'buddy_invite_cancelled',
  'buddy_invite_accepted',
  'buddy_invite_declined',
  'buddy_repeat_change_requested',
  'buddy_repeat_change_accepted',
  'buddy_repeat_change_declined',
  'fly_shop_viewed',
  'fly_pack_selected',
  'fly_pack_purchase_started',
  'fly_pack_purchase_completed',
  'fly_pack_purchase_cancelled',
  'fly_pack_purchase_failed',
  'wishlist_pinned',
  'wishlist_cleared',
  'wishlist_reached',
  'wishlist_opened',
  'home_shop_rail_viewed',
  'home_shop_rail_tapped',
  'tryon_shown',
  'tryon_kept',
  'tryon_dismissed',
  'look_reaction_sent',
  'look_reaction_seen',
  'daily_deals_rerolled',
  'look_saved',
  'look_applied',
  'wishlist_deal_notified',
  'campaign_shown',
  'campaign_clicked',
  'campaign_dismissed',
  'campaign_converted',
  'pact_committed',
  'pact_claimed',
  'pact_skipped',
  'pact_dropped',
  'pact_sessions_removed',
  'pact_retro_claimed',
  'shield_sheet_opened',
  'shield_purchased',
  'fly_circuit_breaker',
  'overflow_jar_gift',
  'buddy_duo_week',
  'friends_pond_weekly_bonus',
] as const;

export type AnalyticsEventName = (typeof ANALYTICS_EVENTS)[number];
export type AnalyticsPlatform = 'web' | 'ios' | 'android' | 'unknown';
export type AnalyticsSource = 'client' | 'server' | 'revenuecat';

export const ANALYTICS_EVENT_SET = new Set<string>(ANALYTICS_EVENTS);

const EVENT_CATEGORIES: Record<AnalyticsEventName, string> = {
  app_opened: 'lifecycle',
  page_viewed: 'lifecycle',
  account_created: 'acquisition',
  onboarding_completed: 'activation',
  starter_plan_shown: 'activation',
  starter_plan_accepted: 'activation',
  starter_plan_skipped: 'activation',
  starter_plan_day_start: 'activation',
  task_created: 'engagement',
  task_completed: 'engagement',
  task_reopened: 'engagement',
  timer_started: 'engagement',
  timer_completed: 'engagement',
  quest_objective_claimed: 'engagement',
  quest_objective_rerolled: 'engagement',
  quest_ladder_finished: 'engagement',
  daily_reward_claimed: 'engagement',
  ad_requested: 'ads',
  ad_ready: 'ads',
  ad_impression: 'ads',
  ad_completed: 'ads',
  ad_dismissed: 'ads',
  ad_failed: 'ads',
  ad_consent_resolved: 'ads',
  ad_consent_failed: 'ads',
  paywall_viewed: 'monetization',
  paywall_step_viewed: 'monetization',
  purchase_started: 'monetization',
  purchase_completed: 'monetization',
  purchase_cancelled: 'monetization',
  purchase_failed: 'monetization',
  subscription_started: 'monetization',
  subscription_renewed: 'monetization',
  subscription_cancelled: 'monetization',
  subscription_expired: 'monetization',
  subscription_billing_issue: 'monetization',
  subscription_refunded: 'monetization',
  subscription_product_changed: 'monetization',
  try_funnel_viewed: 'acquisition',
  try_task_completed: 'activation',
  try_gift_opened: 'activation',
  try_signin_started: 'activation',
  try_signup_completed: 'activation',
  try_gift_claimed: 'activation',
  try_cosmetic_previewed: 'activation',
  try_continued: 'activation',
  try_store_clicked: 'acquisition',
  fly_game_viewed: 'acquisition',
  fly_game_started: 'engagement',
  fly_game_completed: 'engagement',
  fly_game_shared: 'social',
  fly_game_signup_clicked: 'acquisition',
  fly_game_high_score_gift: 'economy',
  fly_game_run_gift: 'economy',
  fly_earned: 'economy',
  fly_spent: 'economy',
  skin_purchased: 'economy',
  skin_traded: 'economy',
  season_reward_claimed: 'economy',
  season_tier_purchased: 'economy',
  referral_invite_created: 'social',
  referral_invite_shared: 'social',
  referral_invite_opened: 'social',
  referral_invite_claimed: 'social',
  friend_link_shared: 'social',
  friend_link_opened: 'social',
  friend_request_sent: 'social',
  friend_request_accepted: 'social',
  friend_request_declined: 'social',
  friend_removed: 'social',
  buddy_flow_opened: 'social',
  buddy_friend_picked: 'social',
  buddy_goal_composed: 'social',
  buddy_invite_sent: 'social',
  buddy_invite_cancelled: 'social',
  buddy_invite_accepted: 'social',
  buddy_invite_declined: 'social',
  buddy_repeat_change_requested: 'social',
  buddy_repeat_change_accepted: 'social',
  buddy_repeat_change_declined: 'social',
  fly_shop_viewed: 'economy',
  fly_pack_selected: 'monetization',
  fly_pack_purchase_started: 'monetization',
  fly_pack_purchase_completed: 'monetization',
  fly_pack_purchase_cancelled: 'monetization',
  fly_pack_purchase_failed: 'monetization',
  wishlist_pinned: 'economy',
  wishlist_cleared: 'economy',
  wishlist_reached: 'economy',
  wishlist_opened: 'economy',
  home_shop_rail_viewed: 'economy',
  home_shop_rail_tapped: 'economy',
  tryon_shown: 'economy',
  tryon_kept: 'economy',
  tryon_dismissed: 'economy',
  look_reaction_sent: 'social',
  look_reaction_seen: 'social',
  daily_deals_rerolled: 'economy',
  look_saved: 'economy',
  look_applied: 'economy',
  campaign_shown: 'monetization',
  campaign_clicked: 'monetization',
  campaign_dismissed: 'monetization',
  campaign_converted: 'monetization',
  wishlist_deal_notified: 'economy',
  pact_committed: 'engagement',
  pact_claimed: 'engagement',
  pact_skipped: 'engagement',
  pact_dropped: 'engagement',
  pact_sessions_removed: 'engagement',
  pact_retro_claimed: 'monetization',
  shield_sheet_opened: 'monetization',
  shield_purchased: 'monetization',
  fly_circuit_breaker: 'economy',
  overflow_jar_gift: 'economy',
  buddy_duo_week: 'social',
  friends_pond_weekly_bonus: 'social',
};

export function analyticsCategory(name: AnalyticsEventName) {
  return EVENT_CATEGORIES[name];
}

const ALLOWED_PROPERTY_KEYS = new Set([
  'page',
  'referrer_host',
  'utm_source',
  'utm_medium',
  'utm_campaign',
  'count',
  'recurring',
  'task_type',
  'tag_count',
  'focus_tag_count',
  'focus_connected',
  'buddy',
  'repeat_mode',
  'checklist_count',
  'has_schedule',
  'has_reminder',
  'streak_tier',
  'streak_length',
  'phase',
  'duration_minutes',
  'focus_duration_minutes',
  'break_duration_minutes',
  'auto_start_breaks',
  'completed_seconds',
  'claim_type',
  'reward_type',
  'reward_amount',
  'reward_count',
  'reward_day',
  'premium_reward_included',
  'quest_placement',
  'quest_category',
  'quest_generation',
  'quest_tier',
  'objective_count',
  'objective_type',
  'objective_subject',
  'objective_action',
  'objective_tag_mode',
  'objective_metric',
  'objective_target',
  'season_id',
  'placement',
  'step',
  'plan',
  'store',
  'environment',
  'product_id',
  'period_type',
  'revenue_usd',
  'proceeds_usd',
  'currency',
  'country',
  'reason',
  'is_trial_conversion',
  'renewal_number',
  'method',
  'source',
  'is_premium',
  'fly_amount',
  'day_key',
  'requested',
  'granted',
  'gifts',
  'gift_item_id',
  'flies_received',
  'flies_spent',
  'item_count',
  'rarity',
  'from_rarity',
  'to_rarity',
  'fuel_rarity',
  'fuel_count',
  'base_fuel_count',
  'fuel_waived',
  'all_spares',
  'aimed',
  'aim_flies',
  'golden',
  'slot',
  'discounted',
  'season_day',
  'season_tier',
  'season_tiers_claimed',
  'free_lanes_claimed',
  'plus_lanes_claimed',
  'tier_count',
  'in_grace_window',
  'pack_id',
  'price_usd',
  'via',
  'action',
  'is_new_user',
  'os',
  'has_buddy_task',
  'gift_option',
  'request_source',
  'share_surface',
  'auto_accepted',
  'response_hours',
  'milestone_tier',
  'bond_streak',
  'score',
  'catches',
  'misses',
  'max_combo',
  'challenge_score',
  'rank',
]);

export function sanitizeAnalyticsProperties(
  value: unknown,
): Record<string, string | number | boolean> {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return {};

  const output: Record<string, string | number | boolean> = {};
  for (const [key, raw] of Object.entries(value)) {
    if (!ALLOWED_PROPERTY_KEYS.has(key)) continue;
    if (typeof raw === 'string') output[key] = raw.trim().slice(0, 120);
    else if (typeof raw === 'number' && Number.isFinite(raw)) output[key] = raw;
    else if (typeof raw === 'boolean') output[key] = raw;
  }
  return output;
}

export function normalizeAnalyticsPage(pathname: string) {
  const clean = pathname.split('?')[0].split('#')[0];
  const segments = clean.split('/').filter(Boolean);
  if (segments[0] === 'admin') return segments[1] ? `/admin/${segments[1]}` : '/admin';
  return segments[0] ? `/${segments[0]}` : '/';
}
