export const FUNNY_SENTENCES = [
  'Hopefully not socks...',
  "Maybe it's a legendary wizard hat?",
  "Is it a fly? I hope it's not a fly.",
  'Please be shiny...',
  'Could it be the golden frog?',
  'Smells like victory...',
  'Shake it! Does it rattle?',
  "I bet it's something green.",
  'Preparing the confetti...',
  'Fingers crossed for epic loot!',
  'Not another fly, please...',
  'Detecting high levels of awesome...',
  'Unlocking happiness...',
];
