import type { MacroCategoryDefinition } from './types';

export const QUEST_MACRO_CATEGORIES: MacroCategoryDefinition[] = [
  {
    id: 'sport',
    name: 'Sport',
    shortLabel: 'Move',
    description: 'Build momentum around movement, recovery, and training.',
    accent: '#22c55e',
    backgroundFrom: '#f59e0b',
    backgroundTo: '#fb7185',
    taskSuggestions: [
      'Plan your next workout',
      'Prep your gym bag',
      'Schedule a walk after lunch',
    ],
    quickAddSuggestions: [
      { emoji: '🏃', text: 'Go for a 20-min walk' },
      { emoji: '💪', text: 'Do 10 push-ups' },
      { emoji: '🧘', text: '5-min stretch' },
      { emoji: '🚴', text: 'Quick bike ride' },
      { emoji: '🏋️', text: "Plan tomorrow's workout" },
      { emoji: '🎒', text: 'Pack gym bag tonight' },
      { emoji: '🥤', text: 'Hit protein target' },
      { emoji: '🧊', text: 'Cold shower after training' },
      { emoji: '📓', text: "Log today's session" },
      { emoji: '🏊', text: 'Book a swim slot' },
      { emoji: '🦵', text: 'Foam-roll legs' },
      { emoji: '🪜', text: 'Take stairs not elevator' },
      { emoji: '⏱️', text: '7-min HIIT' },
      { emoji: '🛌', text: 'Rest day (no training)' },
      { emoji: '📅', text: 'Schedule a long run' },
    ],
    campaignHeadlines: ['Training Sprint', 'Momentum Pass', 'Endurance Push'],
    durationDaysOptions: [7, 14],
    premiumAnimationId: 'sport_victory_bounce',
  },
  {
    id: 'family',
    name: 'Family',
    shortLabel: 'Connect',
    description: 'Protect space for people you care about and shared routines.',
    accent: '#f97316',
    backgroundFrom: '#1d4ed8',
    backgroundTo: '#0f172a',
    taskSuggestions: [
      'Plan quality time with family',
      'Send a thoughtful check-in message',
      'Book a catch-up call',
    ],
    quickAddSuggestions: [
      { emoji: '📞', text: 'Call a parent' },
      { emoji: '💬', text: 'Text a sibling' },
      { emoji: '🍽️', text: 'Plan family dinner' },
      { emoji: '🎁', text: 'Buy a small gift' },
      { emoji: '🚗', text: 'Drive someone somewhere' },
      { emoji: '📸', text: 'Send a photo' },
      { emoji: '🧒', text: 'Read with the kids' },
      { emoji: '🍳', text: 'Cook for someone' },
      { emoji: '📅', text: 'Schedule the visit' },
      { emoji: '❤️', text: 'Say "I love you" today' },
      { emoji: '🎂', text: 'Note an upcoming birthday' },
      { emoji: '🎲', text: 'Game night' },
      { emoji: '🚶', text: 'Walk together' },
      { emoji: '✉️', text: 'Write a thank-you message' },
      { emoji: '📺', text: 'Watch a show together' },
    ],
    campaignHeadlines: ['Connection Bundle', 'Family Focus', 'Together Time'],
    durationDaysOptions: [7, 14],
    premiumAnimationId: 'family_firefly_hug',
  },
  {
    id: 'mindfulness',
    name: 'Mindfulness',
    shortLabel: 'Reset',
    description: 'Slow down, reflect, and make room for consistent calm.',
    accent: '#8b5cf6',
    backgroundFrom: '#06b6d4',
    backgroundTo: '#2563eb',
    taskSuggestions: [
      'Write down one thing you are grateful for',
      'Block a 15-minute reflection session',
      'Create a self-care checklist',
    ],
    quickAddSuggestions: [
      { emoji: '🧘', text: '5-min meditation' },
      { emoji: '📓', text: 'Write 3 gratitudes' },
      { emoji: '🌬️', text: 'Box-breathe 4x4' },
      { emoji: '📵', text: '30-min phone-off' },
      { emoji: '🚶', text: 'Mindful walk' },
      { emoji: '✍️', text: 'Brain-dump journal' },
      { emoji: '🌅', text: 'Watch the sunrise' },
      { emoji: '🎧', text: 'Listen to calm music' },
      { emoji: '🍵', text: 'Slow tea ritual' },
      { emoji: '🧠', text: 'Body scan' },
      { emoji: '🪞', text: 'Affirmation in the mirror' },
      { emoji: '🖐️', text: '5-4-3-2-1 grounding' },
      { emoji: '📖', text: 'Read 10 pages' },
      { emoji: '🎨', text: 'Sketch / doodle' },
      { emoji: '🤐', text: '10 minutes of silence' },
    ],
    campaignHeadlines: ['Calm Mode', 'Mind Garden', 'Grounding Run'],
    durationDaysOptions: [7, 14],
    premiumAnimationId: 'mindfulness_lotus_glow',
  },
  {
    id: 'house_chores',
    name: 'House Chores',
    shortLabel: 'Reset',
    description: 'Turn maintenance work into clear, trackable wins.',
    accent: '#eab308',
    backgroundFrom: '#7c3aed',
    backgroundTo: '#c026d3',
    taskSuggestions: [
      'Reset the kitchen counters',
      'Sort one clutter hotspot',
      'Run one laundry cycle',
    ],
    quickAddSuggestions: [
      { emoji: '🧹', text: 'Sweep one room' },
      { emoji: '🍽️', text: 'Empty the dishwasher' },
      { emoji: '🧺', text: 'Run laundry' },
      { emoji: '🛏️', text: 'Make the bed' },
      { emoji: '🗑️', text: 'Take out trash' },
      { emoji: '🧽', text: 'Wipe kitchen counters' },
      { emoji: '🪟', text: 'Clean a mirror' },
      { emoji: '🚿', text: 'Scrub the shower' },
      { emoji: '🧴', text: 'Restock toiletries' },
      { emoji: '📦', text: 'Sort one drawer' },
      { emoji: '🌱', text: 'Water plants' },
      { emoji: '🛒', text: 'Grocery run' },
      { emoji: '🧾', text: 'Pay one bill' },
      { emoji: '🔌', text: "Unplug what's not in use" },
      { emoji: '🧼', text: '10-min tidy-up' },
    ],
    campaignHeadlines: ['Home Reset', 'Clean Sweep', 'Tidy Track'],
    durationDaysOptions: [7, 14],
    premiumAnimationId: 'chores_sparkle_spin',
  },
  {
    id: 'sleep',
    name: 'Sleep',
    shortLabel: 'Recharge',
    description: 'Support better rest with consistent shutdown routines.',
    accent: '#38bdf8',
    backgroundFrom: '#0f172a',
    backgroundTo: '#1d4ed8',
    taskSuggestions: [
      'Set a wind-down reminder',
      'Prepare tomorrow before bed',
      'Put devices away 30 minutes before sleep',
    ],
    quickAddSuggestions: [
      { emoji: '🌙', text: 'Lights out by 11pm' },
      { emoji: '📵', text: 'Phone away 30 min before bed' },
      { emoji: '🛁', text: 'Warm shower before bed' },
      { emoji: '☕', text: 'No caffeine after 2pm' },
      { emoji: '📖', text: 'Read in bed (no screen)' },
      { emoji: '🧘', text: 'Wind-down breathing' },
      { emoji: '🥛', text: 'No food 2h before bed' },
      { emoji: '🧦', text: 'Cool the room' },
      { emoji: '🌡️', text: 'Set bedroom temp' },
      { emoji: '📓', text: "Write tomorrow's plan" },
      { emoji: '🎧', text: 'Sleep sounds on' },
      { emoji: '⏰', text: 'Wake at same time' },
      { emoji: '☀️', text: 'Morning sunlight in 10 min' },
      { emoji: '🛌', text: 'No work in bed' },
      { emoji: '🚫', text: 'Skip the late nap' },
    ],
    campaignHeadlines: ['Sleep Reset', 'Night Shift', 'Moonlight Routine'],
    durationDaysOptions: [7, 14],
    premiumAnimationId: 'sleep_moon_drift',
  },
];

export function getMacroCategory(categoryId: string) {
  return QUEST_MACRO_CATEGORIES.find((entry) => entry.id === categoryId);
}
